[package]
name = "the_haunted_mansion"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.11.3", features = ["wayland"] }
leafwing-input-manager = "0.10.0"
bevy_ecs_ldtk = "0.8.0"
bevy-inspector-egui = "0.20.0"
lazy_static = "1.4.0"
derivative = "2.2.0"
bevy_asset_loader = { version = "0.17.0", features = ["2d"] }
bevy_rapier2d = "0.22.0"
bevy-ui-dsl = "0.6.1"
bevy_embedded_assets = "0.8.0"
rand = "0.8.5"
futures-lite = "2.0.0"
pathfinding = "4.3.2"

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1

[profile.release]
lto = "thin"